version: '3'
services:
  app:
    container_name: sharelock 
    image: ssiu/sharelock-docker:latest
    build:
      context: ./build
    restart: always
    environment:
      - AUTH0_CALLBACK=http|s://yourserver/callback
      - AUTH0_CLIENT_ID=...auth0 client id....
      - AUTH0_CLIENT_SECRET=...auth0 client secret....
      - AUTH0_DOMAIN=yours.auth0.com
      - COOKIE_SECRET=...32 bytes array in hex...
      - CURRENT_KEY=1
      - ENCRYPTION_KEY_1=...32 bytes array in hex...
      - FORCE_HTTPS=0
      - SIGNATURE_KEY_1=...32 bytes array in hex... 
    ports:
      - "0.0.0.0:3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3


